version: '3.8'

services:
  react-vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: saeedghofrani/react-portfolio:latest
    container_name: react-portfolio
    ports:
      - "12345:12345"          # Host:Container
    restart: unless-stopped
    networks:
      - webnet

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  webnet:
    driver: bridge